name: Deployment
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependency
        run: npm ci
      - name: lint app
        run: npm run lint
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependency
        run: npm ci
      - name: build app
        run: npm run build
      - name: Deploy
        run: echo Deploying...