name: Deployment
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependency
        run: yarn
      - name: lint app
        run: yarn lint
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependency
        run: yarn
      - name: build app
        run: yarn build
      - name: Deploy
        run: echo Deploying...